# Generated by Django 5.0.4 on 2024-05-23 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                    )),
                ('name', models.CharField(
                    error_messages={
                        'unique': 'Task status with such Name already exist.'
                        },
                    max_length=255, unique=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
    ]
