# Generated by Django 5.0.4 on 2024-05-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0001_initial'),
        ('tasks', '0001_initial'),
        ('users', '0002_person_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='author',
                to='users.person',
                verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='executor',
            field=models.ForeignKey(
                blank=True,
                help_text='Select the task executor.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='executor',
                to='users.person',
                verbose_name='Executor'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.ForeignKey(
                help_text='Obligatory field. Select one of the task statuses.',
                on_delete=django.db.models.deletion.PROTECT,
                to='statuses.statusmodel',
                verbose_name='Status'),
        ),
    ]
