# Generated by Django 5.0.6 on 2024-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskmodel_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='status',
        ),
    ]
